[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

build_src_filter =
    +<esp32/>
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv

monitor_speed = 115200
lib_deps = 
    madhephaestus/ESP32Servo 
    mikalhart/TinyGPSPlus 
    https://github.com/AlfredoSystems/AlfredoCRSF 
    adafruit/Adafruit LSM6DS
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    https://github.com/adafruit/Adafruit_LPS2X 


[env:dx-lr30]
platform = ststm32
board = genericSTM32F103C8
framework = arduino

build_src_filter =
    +<dx-lr30/>

upload_protocol = serial
upload_speed = 115200
monitor_speed = 115200